spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rain?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      username: root
      password: chen151732
      initial-size: 5 # 初始化连接池大小
      min-idle: 5 # 最小空闲连接数
      max-active: 20 # 最大活跃连接数

