server:
  port: 8080

spring:
  profiles:
    active: druid
  # 服务模块
  devtools:
    restart:
      enabled: true

mybatis:
  # 扫描所有实体类
  type-aliases-package: org.example.**.domain
  # 扫描所有mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件，配置类位置：framework/config/MyBatisConfig
  config-location: classpath:mybatis-config.xml