server:
  port: 8080

spring:
  profiles:
    active: druid

mybatis:
  # 扫描所有实体类
  typeAliasesPackage: org.example.**.domain
  # 扫描所有mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件，配置类位置：framework/config/MyBatisConfig
  configLocation: classpath:mybatis-config.xml