rain:
  name: Rain
  # 验证码类型 math：数字计算 char：字符验证
  captcha-type: math

server:
  port: 8080

spring:
  profiles:
    active: druid
  # 服务模块
  devtools:
    # 热部署开关
    restart:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms

token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expire-time: 30

mybatis:
  # 扫描所有实体类
  type-aliases-package: com.zainchen.**.domain
  # 扫描所有mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件，配置类位置：framework/config/MyBatisConfig
  config-location: classpath:mybatis-config.xml